CRUD/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('signup', include('signup.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', TemplateView.as_view(template_name = 'home.html'), name = 'home'),
    path('userCRUD/', include('userCRUD.urls', namespace = 'userCRUD'), name = 'userCRUD'),
    path('connection/', include('connection.urls', namespace = 'connection'), name = 'connection'),
]

connection/urls.py
from django.urls import path, include

from . import views


app_name = 'connection'
urlpatterns = [
	path('<int:pk>', views.Select , name = 'Select'),
	path('read/<int:pk>/<str:table>', views.Read, name = 'Read'),
	path('delete/<int:pk>/<int:row>/<str:table>', views.Delete, name = 'Delete'),
	path('create/<int:pk>/<str:table>', views.Create, name = 'Create'),
	path('update/<int:pk>/<int:row>/<str:table>', views.Update, name = 'Update'),
]

signup/urls.py
from django.urls import path

from . import views

urlpatterns = [
	path('', views.SignUp.as_view(), name = 'signup'),
]

userCRUD/urls.py
from django.urls import path
from django.urls import include

from . import views


app_name = 'userCRUD'
urlpatterns = [
	path('create/', views.CreatedbNames, name = 'CreatedbNames'),
	path('read/', views.ReaddbNames, name = 'ReaddbNames'),
	path('edit/<int:pk>', views.EditdbNames, name = 'EditdbNames'),
	path('update/<int:pk>', views.UpdatedbNames, name = 'UpdatedbNames'),
	path('delete/<int:pk>', views.DeletedbNames, name = 'DeletedbNames'),
]

signup/models.py
from django.db import models

# Create your models here.

signup/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic

# Create your views here.

class SignUp(generic.CreateView):
	form_class = UserCreationForm
	success_url = reverse_lazy('login')
	template_name = 'Signup.html'

templates/Create.html
{% extends 'layouts/main.html' %}
{% block title %}Database Connections{% endblock %}

{% block content %}
	<div class="container">
		<form action = "{% url 'connection:Create' pk Table %}" method = "POST" class="user">
			{% csrf_token %}
			{% for col in cList %}
			<div class="form-group row">
				<div class="col-sm-6 mb-3 mb-sm-0">
					<label class="control-label col-sm-2" for="{{ forloop.counter0 }}" >{{ col }}:</label>
					<input type = "text" id = "{{ col }}" name = "{{ col }}" class="form-control form-control-user">
				</div>
			</div>
			{% endfor %}
			<button type="submit" class="btn btn-success">Submit</button>
		</form>
	</div>
{% endblock %}

templates/DBTables.html
{% extends 'layouts/main.html' %}
{% block title %}Database Connections{% endblock %}

{% block heading %}Database Tables{% endblock %}

{% block content %}
    {% csrf_token %}
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Tables</h6>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead class="thead-light">
                    <tr>
                        <th>Table</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for t in tables %}
                    <tr>
                        <td>{{ t }}</td>
                        <td>
                            <a href="{% url 'connection:Read' pk t %}"><i class="far fa-thumbs-up"></i></a>
                        </div>
                        </td>
                    </tr>
                            {% endfor %}
                        
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}


{% block scriptDyn %}
<script>

$(document).ready( function () {
    $('#dataTable').DataTable();
} );
    </script>
          {% endblock %}

templates/Signup.html
<!-- templates/signup.html -->
{% extends 'no-layout.html' %}

{% block title %}Sign Up{% endblock %}

{% block content %}
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}

templates/Update.html
{% extends 'layouts/main.html' %}
{% block title %}Database Connections{% endblock %}

{% block heading %}Update Record{% endblock %}

{% block content %}
	<div class="container">
		<form class="user" action = "{% url 'connection:Update' pk counter Table %}" method = "POST">
			{% csrf_token %}
			{% for col, row in Meta %}
			<div class="form-group row">
				<div class="col-sm-6 mb-3 mb-sm-0">
					<label class="control-label col-sm-2" for="{{ forloop.counter0 }}">{{ col }}</label>
					<input class="form-control form-control-user" type="text" id="{{ col }}" name="{{ col }}" value="{{ row }}" class>
				</div>
			</div>
			{% endfor %}
			<button type="submit" class="btn btn-success">Submit</button>
		</form>
	</div>
{% endblock %}

templates/UpdatedbForm.html
{% extends 'layouts/main.html' %}
{% block title %}Database Connections{% endblock %}

{% load crispy_forms_tags %}


{% block content %}
    <form action="{% url 'userCRUD:UpdatedbNames' id %}" method = "POST">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="submit" class="btn btn-success">
    </form>
{% endblock %}

templates/dbForm.html
{% extends 'layouts/main.html' %}
{% block title %}Database Connections{% endblock %}

{% load crispy_forms_tags %}


{% block content %}
	<div class="container">
		<form action="{% url 'userCRUD:CreatedbNames' %}" method = "POST">
			{% csrf_token %}
			{{ form|crispy }}
		<div>
			<input type="submit" value="submit" class="btn btn-success">
		</div>
		<br>
			<a  class="btn btn-success"href="{% url 'userCRUD:ReaddbNames' %}">Cancel</a>
		</form>
	</div>
{% endblock %}

templates/delete.html
{% extends 'layouts/main.html' %}
{% block title %}Database Connections{% endblock %}

{% block content %}
	<form action="{% url 'userCRUD:DeletedbNames' pk %}" method='POST'>
		{% csrf_token %}
		<p>You sure to delete?</p>
		<input type="submit" value="submit" />
	</form>
{% endblock %}

templates/error.html
{% extends 'layouts/main.html' %}
{% block title %}Database Connections{% endblock %}

{% block heading %}ERROR{% endblock %}

{% block content %}
	<h1>No such Database exists.</h1>
{% endblock %}

templates/home.html
{% extends 'layouts/main.html' %}
{% block title %}Database Connections{% endblock %}

{% block heading %}Database Connections{% endblock %}

{% block content %}
    {% csrf_token %}
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">DataTables Example</h6>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead class="thead-light">
                    <tr>
                        <th>Name</th>
                        <th>Username</th>
                        <th>Password</th>
                        <th>Host</th>
                        <th>Port No.</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for name in DbNames %}
                    <tr>
                        <td>{{ name.dbName }}</td>
                        <td>{{ name.dbUsername }}</td>
                        <td>{{ name.dbPassword }}</td>
                        <td>{{ name.dbHost }}</td>
                        <td>{{ name.dbPort }}</td>
                        <td>
                            <a href="{% url 'connection:Select' name.id %}"><i class="far fa-thumbs-up"></i></a></div>
                            <a href="{% url 'userCRUD:EditdbNames' name.id %}"><i class="fas fa-pencil-alt"></i></a>
                            <a href="{% url 'userCRUD:DeletedbNames' name.id %}"><i class="fas fa-trash-alt"></i></a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </br>
            <div class="row" style="float: left;">
                <div class="col-sm-12" style="margin-bottom: 10px">
                    <a href="{% url 'userCRUD:CreatedbNames' %}" class="btn btn-primary float-right" style="margin-bottom: 10px;" >Add New Record</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block scriptDyn %}
<script>

$(document).ready( function () {
    $('#dataTable').DataTable();
} );
    </script>
          {% endblock %}

templates/main.html
{% extends 'layouts/main.html' %}
{% block title %}Database Connections{% endblock %}

{% block heading %}Table Records{% endblock %}

{% block content %}
    {% csrf_token %}
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Table Entries</h6>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-stripped table-bordered table-hover tblDatatable">
                <thead class="thead-light">
                    <tr>
                    	{% for column in cList %}
                        <th>{{ column }}</th>
                    	{% endfor %}
                    	<th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for row in rows %}
                    <tr>
                    	{% for col in row %}
                    	<td>{{ col }}</td>
                        {% endfor %}
                        <td>
                        	<a href="{% url 'connection:Delete' pk forloop.counter0 Table %}"><i class="fas fa-trash-alt"></i></a>
                            <a href="{% url 'connection:Update' pk forloop.counter0 Table %}"><i class="fas fa-pencil-alt"></i></a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            </br>
            <div class="row">
                <div class="col-sm-12" style="margin-bottom: 10px; float: left;">
                    <a href="{% url 'connection:Create' pk Table %}" class="btn btn-primary float-right">Add New Record</a>
                </div>
            </div>
        </div>
    </div>
</div>
  
   

{% endblock %}

{% block scriptDyn %}
<script>

$(document).ready( function () {
    $('.tblDatatable').DataTable();
} );
    </script>
{% endblock %}